# Generated by Django 6.0 on 2025-12-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=64)),
                ('faction', models.CharField(blank=True, max_length=32, null=True)),
                ('messages', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('voice_minutes', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
