# Generated by Django 6.0 on 2025-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='faction',
        ),
        migrations.AddField(
            model_name='curator',
            name='factions',
            field=models.JSONField(default=list),
        ),
    ]
