# Generated by Django 6.0 on 2025-12-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_curator_faction_curator_factions'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
