# Generated by Django 6.0 on 2025-12-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_curator_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='curator',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
