# Generated by Django 6.0 on 2025-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_curator_updated_at_curator_discord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='nickname',
        ),
        migrations.AddField(
            model_name='curator',
            name='server_nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
