# Generated by Django 6.0 on 2025-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_curator_nickname_curator_server_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='discord_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
