# Generated by Django 6.0 on 2025-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_curator_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='curator_type',
            field=models.CharField(choices=[('government', 'Government'), ('criminal', 'Criminal')], default='government', max_length=20),
            preserve_default=False,
        ),
    ]
