# Generated by Django 6.0 on 2025-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_curator_curator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='curator_type',
        ),
        migrations.AddField(
            model_name='curator',
            name='curator_types',
            field=models.JSONField(default=list),
        ),
    ]
