# Generated by Django 6.0 on 2025-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_curator_curator_type_curator_curator_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, max_length=256, null=True)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
