# Generated by Django 6.0 on 2025-12-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='backup_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='restore_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='restoring',
            field=models.BooleanField(default=False),
        ),
    ]
