# Generated by Django 6.0 on 2025-12-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_server_backup_in_progress_server_restore_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
